[package]
name = "core"
version = "1.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
bitflags = "2.10.0"
bincode = { version = "2.0", features = ["derive"] }
flate2 = "1.1.5"
log = "0.4.29"
log4rs = "1.4.0"
rand = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
