[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
flate2 = "1.0"
chrono = "0.4"
signal-hook = "0.3"
bitflags = "2.4"
log = "0.4.29"
rand = "0.8"
parking_lot = "0.12"

[features]
REAL_CCP = []
KILLERONLY = []