[package]
name = "server"
version = "1.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
flate2 = "1.0"
chrono = "0.4"
bitflags = "2.4"
log = "0.4.29"
rand = "0.8"
ctrlc = "3.5.1"
redis = "1.0.3"
