[build]
rustflags = [
    "-A",
    "clippy::all",
    "-W",
    "clippy::unnecessary_cast",
    "-W",
    "clippy::identity_op",
    "-W",
    "clippy::manual_range_patterns",
    "-W",
    "clippy::clone_on_copy",
    "-W",
    "clippy::large_const_arrays",
    "-W",
    "clippy::explicit_auto_deref",
    "-W",
    "clippy::needless_return",
    "-W",
    "clippy::manual_range_contains",
    "-W",
    "clippy::manual_clamp",
    "-W",
    "clippy::manual_find",
    "-W",
    "clippy::legacy_numeric_constants",
    "-W",
    "clippy::needless_bool",
    "-W",
    "clippy::manual_memcpy",
    "-W",
    "clippy::manual_is_multiple_of",
    "-W",
    "clippy::assign_op_pattern",
    "-W",
    "clippy::needless_borrow",
    "-W",
    "clippy::manual_is_ascii_check",
]
